services:
  backend:
    build:
      context: ./backend
    env_file:
      - .env/.env_db
    depends_on:
      - backend_db
    restart: on-failure
    ports:
      - 8001:8000
    networks:
      - backend_db_network
    volumes:
      - ./backend:/app
  backend_db:
    image: postgres:15.1
    volumes:
      - backend_db_volume:/var/lib/postgresql/data
    env_file:
      - .env/.env_db
    ports:
      - 5433:5432
    networks:
      - backend_db_network

volumes:
  backend_db_volume:

networks:
  backend_db_network:
    driver: bridge