# Generated by Django 4.1.7 on 2023-03-06 19:14

from django.db import migrations, models
import products.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_stock_count_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default='', upload_to='images/', validators=[products.validators.validate_file_type]),
            preserve_default=False,
        ),
    ]
